'use strict';
const crypto=require('crypto');
function coded(code){const error=new Error(code);error.code=code;return error}
function createCommercialService({pool,now=()=>new Date()}){
 async function listSubscriptions(){const [rows]=await pool.query('SELECT s.id,s.instance_id,s.plan_id,s.status,s.starts_at,s.ends_at,s.grace_ends_at,s.version,sp.code AS plan_code,sp.name AS plan_name,pi.subdomain_label,c.display_name AS customer_name FROM subscriptions s JOIN subscription_plans sp ON sp.id=s.plan_id JOIN product_instances pi ON pi.id=s.instance_id JOIN customers c ON c.id=pi.customer_id ORDER BY s.created_at DESC');return rows}
 async function transition(id,input,actorId){const db=await pool.getConnection(),timestamp=now();try{await db.beginTransaction();const [rows]=await db.query('SELECT * FROM subscriptions WHERE id=? FOR UPDATE',[id]);const current=rows[0];if(!current)throw coded('SUBSCRIPTION_NOT_FOUND');if(Number(current.version)!==input.version)throw coded('SUBSCRIPTION_VERSION_CONFLICT');let status=current.status,endsAt=current.ends_at,graceEndsAt=current.grace_ends_at,eventType;
  if(input.action==='RENEW'){const base=new Date(current.ends_at)>timestamp?new Date(current.ends_at):timestamp;endsAt=input.endsAt?new Date(input.endsAt):new Date(base);if(!input.endsAt)endsAt.setUTCMonth(endsAt.getUTCMonth()+Number(input.months||1));if(endsAt<=base)throw coded('SUBSCRIPTION_DATES_INVALID');status='ACTIVE';graceEndsAt=null;eventType='RENEWED'}
  if(input.action==='GRANT_GRACE'){graceEndsAt=new Date(input.graceEndsAt);if(graceEndsAt<=new Date(current.ends_at))throw coded('SUBSCRIPTION_GRACE_INVALID');status='GRACE_PERIOD';eventType='GRACE_STARTED'}
  if(input.action==='SUSPEND'){status='SUSPENDED';eventType='SUSPENDED'}if(input.action==='REACTIVATE'){if(!['SUSPENDED','PAST_DUE','GRACE_PERIOD'].includes(current.status))throw coded('SUBSCRIPTION_NOT_REACTIVATABLE');status=new Date(current.ends_at)>timestamp?'ACTIVE':'PAST_DUE';eventType='REACTIVATED'}if(input.action==='CANCEL'){status='CANCELLED';eventType='CANCELLED'}
  if(['GRANT_GRACE','SUSPEND','CANCEL'].includes(input.action)&&!input.reason)throw coded('SUBSCRIPTION_REASON_REQUIRED');
  const [updated]=await db.query('UPDATE subscriptions SET status=?,ends_at=?,grace_ends_at=?,version=version+1 WHERE id=? AND version=?',[status,endsAt,graceEndsAt,id,input.version]);if(updated.affectedRows!==1)throw coded('SUBSCRIPTION_VERSION_CONFLICT');
  if(['SUSPENDED','CANCELLED'].includes(status)){await db.query('UPDATE product_instances SET status=? WHERE id=?',[status,current.instance_id]);await db.query("UPDATE instance_licenses SET status='REVOKED',revoked_at=?,revoke_reason=? WHERE instance_id=? AND status='ISSUED'",[timestamp,input.reason,current.instance_id])}
  else if(status==='GRACE_PERIOD')await db.query("UPDATE product_instances SET status='GRACE_PERIOD' WHERE id=?",[current.instance_id]);
  else if(status==='ACTIVE')await db.query("UPDATE product_instances SET status='ACTIVE' WHERE id=? AND status<>'PENDING_ACTIVATION'",[current.instance_id]);
  const eventId=crypto.randomUUID();await db.query('INSERT INTO subscription_events (id,subscription_id,instance_id,event_type,actor_id,reason,previous_values_json,new_values_json) VALUES (?,?,?,?,?,?,?,?)',[eventId,id,current.instance_id,eventType,actorId,input.reason||null,JSON.stringify({status:current.status,endsAt:current.ends_at,graceEndsAt:current.grace_ends_at}),JSON.stringify({status,endsAt,graceEndsAt})]);await db.commit();return{id,status,endsAt,graceEndsAt,version:Number(current.version)+1,eventId,eventType,reason:input.reason||null}
 }catch(error){await db.rollback().catch(()=>{});throw error}finally{db.release()}}
 async function listInvoices(){const [rows]=await pool.query('SELECT bi.id,bi.invoice_number,bi.instance_id,bi.status,bi.total,bi.currency,bi.due_at,c.display_name AS customer_name,sp.name AS plan_name,COALESCE(SUM(ip.amount_applied),0) AS amount_paid FROM billing_invoices bi JOIN product_instances pi ON pi.id=bi.instance_id JOIN customers c ON c.id=pi.customer_id JOIN subscription_plans sp ON sp.id=bi.plan_id LEFT JOIN invoice_payments ip ON ip.invoice_id=bi.id GROUP BY bi.id ORDER BY bi.created_at DESC');return rows}
 async function createInvoice(input,actorId){const db=await pool.getConnection(),id=crypto.randomUUID();try{await db.beginTransaction();const [targets]=await db.query('SELECT pi.id,c.legal_name,c.tax_id,sp.id AS plan_id,sp.code,sp.name FROM product_instances pi JOIN customers c ON c.id=pi.customer_id JOIN subscription_plans sp ON sp.id=? AND sp.is_active=TRUE WHERE pi.id=? FOR UPDATE',[input.planId,input.instanceId]);const target=targets[0];if(!target)throw coded('INVOICE_TARGET_NOT_FOUND');const year=now().getUTCFullYear(),[sequences]=await db.query('SELECT next_value FROM billing_sequences WHERE sequence_year=? FOR UPDATE',[year]);let sequence;if(!sequences[0]){sequence=1;await db.query('INSERT INTO billing_sequences (sequence_year,next_value) VALUES (?,2)',[year])}else{sequence=Number(sequences[0].next_value);await db.query('UPDATE billing_sequences SET next_value=next_value+1 WHERE sequence_year=?',[year])}const invoiceNumber='JP-'+year+'-'+String(sequence).padStart(6,'0'),subtotal=Number(input.subtotal),tax=Number(input.tax||0),total=subtotal+tax;
  await db.query("INSERT INTO billing_invoices (id,instance_id,subscription_id,invoice_number,plan_id,billing_interval,period_start,period_end,subtotal,tax,total,currency,status,snapshot_json,issued_at,due_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'ISSUED',?,?,?,?)",[id,input.instanceId,input.subscriptionId||null,invoiceNumber,input.planId,input.billingInterval,new Date(input.periodStart),new Date(input.periodEnd),subtotal,tax,total,input.currency,JSON.stringify({customer:{legalName:target.legal_name,taxId:target.tax_id},plan:{code:target.code,name:target.name}}),now(),new Date(input.dueAt),actorId]);await db.commit();return{id,invoiceNumber,status:'ISSUED',total,currency:input.currency}
 }catch(error){await db.rollback().catch(()=>{});throw error}finally{db.release()}}
 async function registerPayment(input,actorId){const id=crypto.randomUUID();await pool.query('INSERT INTO subscription_payments (id,instance_id,amount,currency,payment_method,reference,paid_at,evidence_url,notes,registered_by) VALUES (?,?,?,?,?,?,?,?,?,?)',[id,input.instanceId,input.amount,input.currency,input.paymentMethod,input.reference||null,new Date(input.paidAt),input.evidenceUrl||null,input.notes||null,actorId]);return{id,status:'PENDING_VERIFICATION'}}
 async function listPayments(){const[rows]=await pool.query('SELECT sp.id,sp.instance_id,sp.amount,sp.currency,sp.payment_method,sp.reference,sp.paid_at,sp.status,sp.evidence_url,sp.rejection_reason,c.display_name AS customer_name,COALESCE(SUM(ip.amount_applied),0) AS amount_applied FROM subscription_payments sp JOIN product_instances pi ON pi.id=sp.instance_id JOIN customers c ON c.id=pi.customer_id LEFT JOIN invoice_payments ip ON ip.payment_id=sp.id GROUP BY sp.id ORDER BY sp.created_at DESC');return rows}
 async function verifyPayment(paymentId,input,actorId){const db=await pool.getConnection(),timestamp=now();try{await db.beginTransaction();const [payments]=await db.query('SELECT * FROM subscription_payments WHERE id=? FOR UPDATE',[paymentId]);const payment=payments[0];if(!payment||!['PENDING_VERIFICATION','CONFIRMED'].includes(payment.status))throw coded('PAYMENT_NOT_VERIFIABLE');if(!input.confirmed){if(payment.status!=='PENDING_VERIFICATION')throw coded('PAYMENT_NOT_REJECTABLE');if(!input.reason)throw coded('PAYMENT_REJECTION_REASON_REQUIRED');await db.query("UPDATE subscription_payments SET status='REJECTED',verified_by=?,verified_at=?,rejection_reason=? WHERE id=?",[actorId,timestamp,input.reason,paymentId]);await db.commit();return{id:paymentId,status:'REJECTED'}}
  const [invoices]=await db.query('SELECT * FROM billing_invoices WHERE id=? FOR UPDATE',[input.invoiceId]),invoice=invoices[0];if(!invoice||invoice.instance_id!==payment.instance_id||invoice.currency!==payment.currency||!['ISSUED','PARTIALLY_PAID'].includes(invoice.status))throw coded('PAYMENT_INVOICE_INVALID');const [[paid]]=await db.query('SELECT COALESCE(SUM(amount_applied),0) AS total FROM invoice_payments WHERE invoice_id=?',[input.invoiceId]);const [[used]]=await db.query('SELECT COALESCE(SUM(amount_applied),0) AS total FROM invoice_payments WHERE payment_id=?',[paymentId]);const amount=Number(input.amountApplied),remaining=Math.min(Number(payment.amount)-Number(used.total),Number(invoice.total)-Number(paid.total));if(amount<=0||amount>remaining)throw coded('PAYMENT_APPLICATION_INVALID');await db.query('INSERT INTO invoice_payments (invoice_id,payment_id,amount_applied) VALUES (?,?,?)',[input.invoiceId,paymentId,amount]);const full=Math.abs(Number(invoice.total)-Number(paid.total)-amount)<0.005;await db.query('UPDATE billing_invoices SET status=?,paid_at=? WHERE id=?',[full?'PAID':'PARTIALLY_PAID',full?timestamp:null,input.invoiceId]);await db.query("UPDATE subscription_payments SET status='CONFIRMED',verified_by=COALESCE(verified_by,?),verified_at=COALESCE(verified_at,?) WHERE id=?",[actorId,timestamp,paymentId]);if(full&&invoice.subscription_id){const [subscriptions]=await db.query('SELECT * FROM subscriptions WHERE id=? FOR UPDATE',[invoice.subscription_id]),subscription=subscriptions[0];if(subscription){const renewedUntil=new Date(subscription.ends_at)>new Date(invoice.period_end)?subscription.ends_at:invoice.period_end;await db.query("UPDATE subscriptions SET status='ACTIVE',ends_at=?,grace_ends_at=NULL,version=version+1 WHERE id=?",[renewedUntil,subscription.id]);await db.query("INSERT INTO subscription_events (id,subscription_id,instance_id,event_type,actor_id,reason,previous_values_json,new_values_json) VALUES (?,?,?,'RENEWED',?,?,?,?)",[crypto.randomUUID(),subscription.id,subscription.instance_id,actorId,'Factura pagada '+invoice.invoice_number,JSON.stringify({status:subscription.status,endsAt:subscription.ends_at}),JSON.stringify({status:'ACTIVE',endsAt:renewedUntil})])}}await db.commit();return{id:paymentId,status:'CONFIRMED',invoiceStatus:full?'PAID':'PARTIALLY_PAID'}
 }catch(error){await db.rollback().catch(()=>{});throw error}finally{db.release()}}
 async function reconcileExpirations(){const [rows]=await pool.query("SELECT id FROM subscriptions WHERE status IN ('TRIAL','ACTIVE','GRACE_PERIOD') AND ((status IN ('TRIAL','ACTIVE') AND ends_at<=?) OR (status='GRACE_PERIOD' AND grace_ends_at<=?))",[now(),now()]);const events=[];for(const item of rows){const db=await pool.getConnection();try{await db.beginTransaction();const [locked]=await db.query('SELECT * FROM subscriptions WHERE id=? FOR UPDATE',[item.id]),current=locked[0];if(!current){await db.rollback();continue}const expired=(['TRIAL','ACTIVE'].includes(current.status)&&new Date(current.ends_at)<=now())||(current.status==='GRACE_PERIOD'&&new Date(current.grace_ends_at)<=now());if(!expired){await db.rollback();continue}await db.query("UPDATE subscriptions SET status='PAST_DUE',version=version+1 WHERE id=?",[current.id]);await db.query("UPDATE product_instances SET status='PAST_DUE' WHERE id=?",[current.instance_id]);await db.query("UPDATE instance_licenses SET status='REVOKED',revoked_at=?,revoke_reason='SUBSCRIPTION_EXPIRED' WHERE instance_id=? AND status='ISSUED'",[now(),current.instance_id]);const eventId=crypto.randomUUID();await db.query("INSERT INTO subscription_events (id,subscription_id,instance_id,event_type,actor_id,reason,previous_values_json,new_values_json) VALUES (?,?,?,'EXPIRED',NULL,'SUBSCRIPTION_EXPIRED',?,?)",[eventId,current.id,current.instance_id,JSON.stringify({status:current.status}),JSON.stringify({status:'PAST_DUE'})]);await db.commit();events.push({subscriptionId:current.id,eventId,eventType:'EXPIRED',reason:'SUBSCRIPTION_EXPIRED'})}catch(error){await db.rollback().catch(()=>{});throw error}finally{db.release()}}return{reconciled:events.length,events}}
 return{listSubscriptions,transition,listInvoices,createInvoice,registerPayment,listPayments,verifyPayment,reconcileExpirations}
}
module.exports={createCommercialService};
