'use strict';
const crypto=require('crypto');
const {encryptPlatformSecret,decryptPlatformSecret}=require('../domain/platformSecrets');
function createNotificationDeliveryService({pool,encryptionKey,providers,templates,now=()=>new Date()}){
 async function queueWelcome(instanceId,activation){
  const [rows]=await pool.query("SELECT pi.id,pi.subdomain_label,pi.public_ip,na.management_cidr,c.id AS customer_id,c.display_name,cc.full_name,cc.email,ps.setting_value AS root_domain FROM product_instances pi JOIN customers c ON c.id=pi.customer_id JOIN customer_contacts cc ON cc.customer_id=c.id AND cc.is_primary=TRUE AND cc.status='ACTIVE' LEFT JOIN network_allocations na ON na.instance_id=pi.id JOIN platform_settings ps ON ps.setting_key='root_domain' WHERE pi.id=?",[instanceId]);const data=rows[0];if(!data)return{queued:false,reason:'WELCOME_CONTACT_NOT_FOUND'};
  const id=crypto.randomUUID(),idempotencyKey=crypto.createHash('sha256').update('WELCOME:'+activation.id).digest('hex');
  const payload={contactName:data.full_name,customerName:data.display_name,fqdn:data.subdomain_label+'.'+data.root_domain,publicIp:data.public_ip||null,managementCidr:data.management_cidr,expiresAt:activation.expiresAt,manualUrl:'https://central.'+data.root_domain+'/manual/instalacion?v=1'};
  const secret=encryptPlatformSecret(JSON.stringify({activationCode:activation.code}),encryptionKey,'notification-delivery:'+id);
  try{await pool.query("INSERT INTO notification_deliveries (id,customer_id,instance_id,template_key,channel,recipient,payload_json,payload_secret_encrypted,idempotency_key,status,next_attempt_at) VALUES (?,?,?,'CUSTOMER_WELCOME','EMAIL',?,?,?,?,'QUEUED',?)",[id,data.customer_id,instanceId,data.email,JSON.stringify(payload),secret,idempotencyKey,now()]);return{id,queued:true}}
  catch(error){if(error.code==='ER_DUP_ENTRY')return{queued:false,reason:'WELCOME_ALREADY_QUEUED'};throw error}
 }
 async function processDue(limit=10){const [rows]=await pool.query("SELECT id FROM notification_deliveries WHERE status IN ('QUEUED','RETRY') AND next_attempt_at<=? ORDER BY created_at LIMIT ?",[now(),limit]);const results=[];for(const row of rows)results.push(await deliver(row.id));return results}
 async function deliver(id){const db=await pool.getConnection();let delivery;try{await db.beginTransaction();const [rows]=await db.query('SELECT * FROM notification_deliveries WHERE id=? FOR UPDATE',[id]);delivery=rows[0];if(!delivery||!['QUEUED','RETRY'].includes(delivery.status)||new Date(delivery.next_attempt_at)>now()){await db.rollback();return{id,skipped:true}}await db.query("UPDATE notification_deliveries SET status='PROCESSING',attempts=attempts+1,last_attempt_at=? WHERE id=?",[now(),id]);await db.commit()}catch(error){await db.rollback().catch(()=>{});throw error}finally{db.release()}
  try{const payload=typeof delivery.payload_json==='string'?JSON.parse(delivery.payload_json):delivery.payload_json;const secret=JSON.parse(decryptPlatformSecret(delivery.payload_secret_encrypted,encryptionKey,'notification-delivery:'+id));const {row,config,transporter}=await providers.transporterAndProvider();const template=await templates.active(delivery.template_key,delivery.channel,'es-PE');if(!template){const e=new Error('TEMPLATE_NOT_CONFIGURED');e.code=e.message;throw e}const data={...payload,activationCode:secret.activationCode,publicIp:payload.publicIp||'pendiente',expiresAt:new Date(payload.expiresAt).toLocaleString('es-PE',{timeZone:'America/Lima'})};const subject=templates.render(template.subject_template,data),text=templates.render(template.body_text_template,data);await transporter.sendMail({to:delivery.recipient,from:{name:config.fromName,address:config.fromEmail},replyTo:config.replyTo||undefined,subject,text});await pool.query("UPDATE notification_deliveries SET status='DELIVERED',delivered_at=?,last_error_code=NULL,payload_secret_encrypted=NULL WHERE id=?",[now(),id]);await pool.query("UPDATE notification_providers SET status='HEALTHY',last_success_at=?,last_error_code=NULL WHERE id=?",[now(),row.id]);return{id,delivered:true}}
  catch(error){const attempts=Number(delivery.attempts)+1,failed=attempts>=5,delayMinutes=[1,5,15,60,240][Math.min(attempts-1,4)];await pool.query("UPDATE notification_deliveries SET status=?,next_attempt_at=?,last_error_code=? WHERE id=?",[failed?'FAILED':'RETRY',new Date(now().getTime()+delayMinutes*60000),String(error.code||'DELIVERY_FAILED').slice(0,80),id]);return{id,delivered:false,retry:!failed}}
 }
 async function listDeliveries(){const [rows]=await pool.query('SELECT id,customer_id,instance_id,template_key,channel,recipient,status,attempts,next_attempt_at,last_attempt_at,delivered_at,last_error_code,created_at FROM notification_deliveries ORDER BY created_at DESC LIMIT 200');return rows}
 async function retry(id){const [result]=await pool.query("UPDATE notification_deliveries SET status='QUEUED',next_attempt_at=?,last_error_code=NULL WHERE id=? AND status='FAILED'",[now(),id]);if(result.affectedRows!==1){const error=new Error('DELIVERY_NOT_RETRYABLE');error.code='DELIVERY_NOT_RETRYABLE';throw error}return{id,status:'QUEUED'}}
 return{queueWelcome,processDue,listDeliveries,retry}
}
module.exports={createNotificationDeliveryService};
