'use strict';
const crypto=require('crypto');
const {encryptPlatformSecret,decryptPlatformSecret}=require('../domain/platformSecrets');
function createNotificationDeliveryService({pool,encryptionKey,providers,templates,now=()=>new Date()}){
 async function queueWelcome(instanceId,activation){
  const [rows]=await pool.query("SELECT pi.id,pi.subdomain_label,pi.public_ip,na.management_cidr,c.id AS customer_id,c.display_name,cc.full_name,cc.email,ps.setting_value AS root_domain FROM product_instances pi JOIN customers c ON c.id=pi.customer_id JOIN customer_contacts cc ON cc.customer_id=c.id AND cc.is_primary=TRUE AND cc.status='ACTIVE' LEFT JOIN network_allocations na ON na.instance_id=pi.id JOIN platform_settings ps ON ps.setting_key='root_domain' WHERE pi.id=?",[instanceId]);const data=rows[0];if(!data)return{queued:false,reason:'WELCOME_CONTACT_NOT_FOUND'};
  const id=crypto.randomUUID(),idempotencyKey=crypto.createHash('sha256').update('WELCOME:'+activation.id).digest('hex');
  const payload={contactName:data.full_name,customerName:data.display_name,fqdn:data.subdomain_label+'.'+data.root_domain,publicIp:data.public_ip||null,managementCidr:data.management_cidr,expiresAt:activation.expiresAt,manualUrl:'https://central.'+data.root_domain+'/manual/instalacion?v=1'};
  const secret=encryptPlatformSecret(JSON.stringify({activationCode:activation.code}),encryptionKey,'notification-delivery:'+id);
  try{await pool.query("INSERT INTO notification_deliveries (id,customer_id,instance_id,template_key,channel,recipient,payload_json,payload_secret_encrypted,idempotency_key,status,next_attempt_at) VALUES (?,?,?,'CUSTOMER_WELCOME','EMAIL',?,?,?,?,'QUEUED',?)",[id,data.customer_id,instanceId,data.email,JSON.stringify(payload),secret,idempotencyKey,now()]);return{id,queued:true}}
  catch(error){if(error.code==='ER_DUP_ENTRY')return{queued:false,reason:'WELCOME_ALREADY_QUEUED'};throw error}
 }
 async function queueSubscriptionEvent(subscriptionId,event){
  const templateByEvent={RENEWED:'SUBSCRIPTION_RENEWED',GRACE_STARTED:'SUBSCRIPTION_GRACE_STARTED',SUSPENDED:'SUBSCRIPTION_SUSPENDED',REACTIVATED:'SUBSCRIPTION_REACTIVATED',CANCELLED:'SUBSCRIPTION_CANCELLED',EXPIRED:'SUBSCRIPTION_EXPIRED'};
  const templateKey=templateByEvent[event.eventType];if(!templateKey)return{queued:false,reason:'EVENT_NOT_NOTIFIABLE'};
  const [rows]=await pool.query("SELECT s.id,s.status,s.ends_at,s.grace_ends_at,sp.name AS plan_name,pi.id AS instance_id,pi.subdomain_label,c.id AS customer_id,c.display_name,cc.full_name,cc.email,ps.setting_value AS root_domain FROM subscriptions s JOIN subscription_plans sp ON sp.id=s.plan_id JOIN product_instances pi ON pi.id=s.instance_id JOIN customers c ON c.id=pi.customer_id JOIN customer_contacts cc ON cc.customer_id=c.id AND cc.is_primary=TRUE AND cc.status='ACTIVE' JOIN platform_settings ps ON ps.setting_key='root_domain' WHERE s.id=?",[subscriptionId]);const data=rows[0];if(!data)return{queued:false,reason:'SUBSCRIPTION_CONTACT_NOT_FOUND'};
  const id=crypto.randomUUID(),idempotencyKey=crypto.createHash('sha256').update('SUBSCRIPTION:'+event.eventId).digest('hex');
  const eventNames={RENEWED:'Membresía renovada',GRACE_STARTED:'Periodo de gracia iniciado',SUSPENDED:'Membresía suspendida',REACTIVATED:'Membresía reactivada',CANCELLED:'Membresía cancelada',EXPIRED:'Membresía vencida'};
  const payload={contactName:data.full_name,customerName:data.display_name,fqdn:data.subdomain_label+'.'+data.root_domain,planName:data.plan_name,status:data.status,endsAt:data.ends_at,graceEndsAt:data.grace_ends_at,reason:event.reason||'',eventName:eventNames[event.eventType]};
  try{await pool.query("INSERT INTO notification_deliveries (id,customer_id,instance_id,template_key,channel,recipient,payload_json,payload_secret_encrypted,idempotency_key,status,next_attempt_at) VALUES (?,?,?,?, 'EMAIL',?,?,NULL,?,'QUEUED',?)",[id,data.customer_id,data.instance_id,templateKey,data.email,JSON.stringify(payload),idempotencyKey,now()]);return{id,queued:true}}
  catch(error){if(error.code==='ER_DUP_ENTRY')return{queued:false,reason:'EVENT_ALREADY_QUEUED'};throw error}
 }
 async function insertEventDelivery(data,templateKey,eventId,payload){
  const id=crypto.randomUUID(),idempotencyKey=crypto.createHash('sha256').update(templateKey+':'+eventId).digest('hex');
  try{await pool.query("INSERT INTO notification_deliveries (id,customer_id,instance_id,template_key,channel,recipient,payload_json,payload_secret_encrypted,idempotency_key,status,next_attempt_at) VALUES (?,?,?,?, 'EMAIL',?,?,NULL,?,'QUEUED',?)",[id,data.customer_id,data.instance_id,templateKey,data.email,JSON.stringify(payload),idempotencyKey,now()]);return{id,queued:true}}
  catch(error){if(error.code==='ER_DUP_ENTRY')return{queued:false,reason:'EVENT_ALREADY_QUEUED'};throw error}
 }
 async function queueInvoiceEvent(invoiceId,eventType,eventId=invoiceId){
  if(!['INVOICE_ISSUED','INVOICE_OVERDUE'].includes(eventType))return{queued:false,reason:'EVENT_NOT_NOTIFIABLE'};
  const [rows]=await pool.query("SELECT bi.id,bi.invoice_number,bi.total,bi.currency,bi.due_at,sp.name AS plan_name,pi.id AS instance_id,pi.subdomain_label,c.id AS customer_id,c.display_name,cc.full_name,cc.email,ps.setting_value AS root_domain,cs.payment_instructions FROM billing_invoices bi JOIN subscription_plans sp ON sp.id=bi.plan_id JOIN product_instances pi ON pi.id=bi.instance_id JOIN customers c ON c.id=pi.customer_id JOIN customer_contacts cc ON cc.customer_id=c.id AND cc.is_primary=TRUE AND cc.status='ACTIVE' JOIN platform_settings ps ON ps.setting_key='root_domain' JOIN commercial_settings cs ON cs.id=1 WHERE bi.id=?",[invoiceId]);const data=rows[0];if(!data)return{queued:false,reason:'INVOICE_CONTACT_NOT_FOUND'};
  return insertEventDelivery(data,eventType,eventId,{contactName:data.full_name,customerName:data.display_name,fqdn:data.subdomain_label+'.'+data.root_domain,planName:data.plan_name,invoiceNumber:data.invoice_number,total:Number(data.total).toFixed(2),currency:data.currency,dueAt:data.due_at,paymentInstructions:data.payment_instructions||''});
 }
 async function queuePaymentEvent(paymentId,eventType,event){
  if(!['PAYMENT_CONFIRMED','PAYMENT_REJECTED'].includes(eventType))return{queued:false,reason:'EVENT_NOT_NOTIFIABLE'};
  const [rows]=await pool.query("SELECT sp.id,sp.amount,sp.currency,sp.payment_method,pi.id AS instance_id,pi.subdomain_label,c.id AS customer_id,c.display_name,cc.full_name,cc.email,ps.setting_value AS root_domain,bi.invoice_number FROM subscription_payments sp JOIN product_instances pi ON pi.id=sp.instance_id JOIN customers c ON c.id=pi.customer_id JOIN customer_contacts cc ON cc.customer_id=c.id AND cc.is_primary=TRUE AND cc.status='ACTIVE' JOIN platform_settings ps ON ps.setting_key='root_domain' LEFT JOIN billing_invoices bi ON bi.id=? WHERE sp.id=?",[event.invoiceId||null,paymentId]);const data=rows[0];if(!data)return{queued:false,reason:'PAYMENT_CONTACT_NOT_FOUND'};
  return insertEventDelivery(data,eventType,event.eventId||eventType+':'+paymentId,{contactName:data.full_name,customerName:data.display_name,fqdn:data.subdomain_label+'.'+data.root_domain,invoiceNumber:data.invoice_number||'no aplica',amount:Number(data.amount).toFixed(2),currency:data.currency,paymentMethod:data.payment_method,reason:event.reason||''});
 }
 async function processDue(limit=10){const [rows]=await pool.query("SELECT id FROM notification_deliveries WHERE status IN ('QUEUED','RETRY') AND next_attempt_at<=? ORDER BY created_at LIMIT ?",[now(),limit]);const results=[];for(const row of rows)results.push(await deliver(row.id));return results}
 async function deliver(id){const db=await pool.getConnection();let delivery;try{await db.beginTransaction();const [rows]=await db.query('SELECT * FROM notification_deliveries WHERE id=? FOR UPDATE',[id]);delivery=rows[0];if(!delivery||!['QUEUED','RETRY'].includes(delivery.status)||new Date(delivery.next_attempt_at)>now()){await db.rollback();return{id,skipped:true}}await db.query("UPDATE notification_deliveries SET status='PROCESSING',attempts=attempts+1,last_attempt_at=? WHERE id=?",[now(),id]);await db.commit()}catch(error){await db.rollback().catch(()=>{});throw error}finally{db.release()}
  try{const payload=typeof delivery.payload_json==='string'?JSON.parse(delivery.payload_json):delivery.payload_json;const secret=delivery.payload_secret_encrypted?JSON.parse(decryptPlatformSecret(delivery.payload_secret_encrypted,encryptionKey,'notification-delivery:'+id)):{};const {row,config,transporter}=await providers.transporterAndProvider();const template=await templates.active(delivery.template_key,delivery.channel,'es-PE');if(!template){const e=new Error('TEMPLATE_NOT_CONFIGURED');e.code=e.message;throw e}const formatDate=(value)=>value?new Date(value).toLocaleString('es-PE',{timeZone:'America/Lima'}):'no aplica';const data={...payload,...secret,publicIp:payload.publicIp||'pendiente',expiresAt:formatDate(payload.expiresAt),endsAt:formatDate(payload.endsAt),graceEndsAt:formatDate(payload.graceEndsAt)};const subject=templates.render(template.subject_template,data),text=templates.render(template.body_text_template,data);await transporter.sendMail({to:delivery.recipient,from:{name:config.fromName,address:config.fromEmail},replyTo:config.replyTo||undefined,subject,text});await pool.query("UPDATE notification_deliveries SET status='DELIVERED',delivered_at=?,last_error_code=NULL,payload_secret_encrypted=NULL WHERE id=?",[now(),id]);await pool.query("UPDATE notification_providers SET status='HEALTHY',last_success_at=?,last_error_code=NULL WHERE id=?",[now(),row.id]);return{id,delivered:true}}
  catch(error){const attempts=Number(delivery.attempts)+1,failed=attempts>=5,delayMinutes=[1,5,15,60,240][Math.min(attempts-1,4)];await pool.query("UPDATE notification_deliveries SET status=?,next_attempt_at=?,last_error_code=? WHERE id=?",[failed?'FAILED':'RETRY',new Date(now().getTime()+delayMinutes*60000),String(error.code||'DELIVERY_FAILED').slice(0,80),id]);return{id,delivered:false,retry:!failed}}
 }
 async function listDeliveries(){const [rows]=await pool.query('SELECT id,customer_id,instance_id,template_key,channel,recipient,status,attempts,next_attempt_at,last_attempt_at,delivered_at,last_error_code,created_at FROM notification_deliveries ORDER BY created_at DESC LIMIT 200');return rows}
 async function retry(id){const [result]=await pool.query("UPDATE notification_deliveries SET status='QUEUED',next_attempt_at=?,last_error_code=NULL WHERE id=? AND status='FAILED'",[now(),id]);if(result.affectedRows!==1){const error=new Error('DELIVERY_NOT_RETRYABLE');error.code='DELIVERY_NOT_RETRYABLE';throw error}return{id,status:'QUEUED'}}
 return{queueWelcome,queueSubscriptionEvent,queueInvoiceEvent,queuePaymentEvent,processDue,listDeliveries,retry}
}
module.exports={createNotificationDeliveryService};
