import { useCallback, useEffect, useState } from 'react';
import { ChevronRight, ExternalLink, FolderPlus, Loader2, Plus, RefreshCw, Users } from 'lucide-react';
import { integrationsApi, type IntegrationGuide, type TelegramForumGroup, type TelegramForumParticipant, type TelegramForumTopic } from '../../../../services/integrationsApi';

const label = (value: string) => value === 'ACTIVE' ? 'Activo' : value === 'CLOSED' ? 'Cerrado' : value.replaceAll('_', ' ').toLowerCase();

export default function TelegramForums({ standalone = false }: { standalone?: boolean }) {
  return standalone ? <TelegramForumsContent /> : null;
}

function TelegramForumsContent() {
  const [groups, setGroups] = useState<TelegramForumGroup[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [topics, setTopics] = useState<TelegramForumTopic[]>([]);
  const [participants, setParticipants] = useState<TelegramForumParticipant[]>([]);
  const [guide, setGuide] = useState<IntegrationGuide | null>(null);
  const [link, setLink] = useState<{ command: string; expiresAt: number } | null>(null);
  const [addingGroup, setAddingGroup] = useState(false);
  const [addingTopic, setAddingTopic] = useState(false);
  const [clientId, setClientId] = useState('');
  const [preview, setPreview] = useState<{ client: { id: string; name: string }; topicName: string } | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  const load = useCallback(async () => {
    const result = await integrationsApi.listTelegramForums();
    setGroups(result.groups);
    setSelected(current => result.groups.some(group => group.id === current && group.status === 'ACTIVE') ? current : result.groups.find(group => group.status === 'ACTIVE')?.id || null);
  }, []);
  useEffect(() => { void load().catch(() => setMessage('No se pudieron cargar los grupos.')); void integrationsApi.getMikrowispGuide().then(result => setGuide(result.guide)).catch(() => null); }, [load]);
  useEffect(() => {
    if (!selected) { setTopics([]); setParticipants([]); return; }
    void Promise.all([integrationsApi.listTelegramForumTopics(selected), integrationsApi.listTelegramForumParticipants(selected)])
      .then(([a, b]) => { setTopics(a.topics); setParticipants(b.participants); })
      .catch(() => setMessage('No se pudieron cargar los temas o participantes.'));
  }, [selected]);

  const generateLink = async () => { setBusy(true); setMessage(null); try { const r = await integrationsApi.createTelegramForumLink(); setLink(r.link); setMessage('Código generado. Envíalo dentro del supergrupo antes de que venza.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo generar el código.'); } finally { setBusy(false); } };
  const validateClient = async () => { if (!selected) return; setBusy(true); setMessage(null); try { setPreview((await integrationsApi.previewTelegramForumTopic(selected, clientId)).preview); } catch (e) { setPreview(null); setMessage(e instanceof Error ? e.message : 'No se pudo validar el cliente.'); } finally { setBusy(false); } };
  const createTopic = async () => { if (!selected || !preview) return; setBusy(true); setMessage(null); try { const r = await integrationsApi.createTelegramForumTopic(selected, preview.client.id); setTopics(v => [r.topic, ...v]); setPreview(null); setClientId(''); setAddingTopic(false); setMessage('Tema creado y confirmado por Telegram.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo crear el tema.'); } finally { setBusy(false); } };
  const changeTopic = async (topic: TelegramForumTopic, action: 'close' | 'reopen') => { if (!selected) return; setBusy(true); try { const r = await integrationsApi.changeTelegramForumTopic(selected, topic.id, action); setTopics(v => v.map(item => item.id === topic.id ? r.topic : item)); } catch (e) { setMessage(e instanceof Error ? e.message : 'Telegram no confirmó la operación.'); } finally { setBusy(false); } };
  const recreate = async (topic: TelegramForumTopic) => { if (!selected || !window.confirm(`¿Recrear el tema “${topic.name}”? Verifica primero en Telegram que no exista.`)) return; setBusy(true); try { const r = await integrationsApi.recreateTelegramForumTopic(selected, topic.id); setTopics(v => v.map(item => item.id === topic.id ? r.topic : item)); } catch (e) { setMessage(e instanceof Error ? e.message : 'Telegram no confirmó la recreación.'); } finally { setBusy(false); } };
  const participantAction = async (p: TelegramForumParticipant, action: 'invite' | 'remove' | 'reinstate') => {
    if (!selected) return;
    if (action === 'remove' && !window.confirm(`¿Retirar a ${p.name || p.email} del grupo completo?`)) return;
    if (action === 'reinstate' && !window.confirm(`¿Reintegrar a ${p.name || p.email}?`)) return;
    setBusy(true); try { const r = action === 'invite' ? await integrationsApi.inviteTelegramForumParticipant(selected, p.userId) : action === 'remove' ? await integrationsApi.removeTelegramForumParticipant(selected, p.userId) : await integrationsApi.reinstateTelegramForumParticipant(selected, p.userId); setParticipants(v => v.map(item => item.userId === p.userId ? { ...item, ...r.participant } : item)); setMessage(action === 'remove' ? 'Participante retirado.' : 'Invitación individual creada.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo completar la operación.'); } finally { setBusy(false); }
  };
  const currentGroup = groups.find(group => group.id === selected) || null;

  return <div className="space-y-4 rounded-xl border border-violet-200 bg-violet-50 p-3 dark:border-violet-800/60 dark:bg-violet-500/10">

    <section className="rounded-xl bg-white p-3 dark:bg-slate-900" aria-labelledby="groups-heading">
      <div className="flex items-center justify-between gap-3"><div><h3 id="groups-heading" className="text-sm font-bold text-slate-900 dark:text-white">Mis grupos</h3><p className="mt-1 text-xs text-slate-500">Selecciona un grupo para ver sus temas.</p></div><button type="button" aria-label="Actualizar grupos" onClick={() => void load()} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-lg border border-slate-200 dark:border-slate-700"><RefreshCw className="h-4 w-4" /></button></div>
      {groups.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2">{groups.map(group => <button key={group.id} type="button" disabled={group.status !== 'ACTIVE'} aria-pressed={group.id === selected} onClick={() => { setSelected(group.id); setAddingTopic(false); }} className={`flex min-h-16 items-center justify-between rounded-xl border p-3 text-left transition disabled:opacity-60 ${group.id === selected ? 'border-violet-500 bg-violet-50 ring-2 ring-violet-500/15 dark:bg-violet-500/10' : 'border-slate-200 hover:border-violet-300 dark:border-slate-700'}`}><span className="min-w-0"><span className="block truncate text-sm font-semibold">{group.name || 'Pendiente de vincular'}</span><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[11px] font-semibold ${group.status === 'ACTIVE' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300' : 'bg-amber-50 text-amber-700'}`}>{label(group.status)}</span></span><ChevronRight className="h-4 w-4 shrink-0 text-slate-400" /></button>)}</div> : <div className="mt-3 rounded-lg border border-dashed border-slate-300 p-5 text-center text-xs text-slate-500 dark:border-slate-700">Todavía no hay grupos vinculados.</div>}
    </section>

    {currentGroup ? <section className="space-y-4 rounded-xl bg-white p-3 dark:bg-slate-900" aria-labelledby="group-detail-heading">
      <div className="flex items-center justify-between border-b border-slate-100 pb-3 dark:border-slate-800"><div><p className="text-xs font-semibold uppercase tracking-wide text-violet-600">Grupo seleccionado</p><h3 id="group-detail-heading" className="mt-1 text-base font-bold">{currentGroup.name}</h3></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300">Activo</span></div>
      <div><div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-bold">Temas del grupo</h4><p className="mt-1 text-xs text-slate-500">{topics.length} {topics.length === 1 ? 'tema registrado' : 'temas registrados'}</p></div><button type="button" onClick={() => setAddingTopic(v => !v)} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-violet-200 px-3 text-xs font-semibold text-violet-700"><Plus className="h-4 w-4" />Nuevo tema</button></div>
        <div className="mt-3 space-y-2">{topics.length ? topics.map(topic => <div key={topic.id} className="flex flex-col gap-2 rounded-lg border border-slate-200 p-3 text-xs dark:border-slate-700 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{topic.name}</p><p className="mt-1 text-slate-500">Thread {topic.threadId || 'sin confirmar'} · {label(topic.status)}</p></div>{topic.status === 'ACTIVE' ? <button type="button" disabled={busy} onClick={() => void changeTopic(topic, 'close')} className="min-h-10 rounded-lg border px-3">Cerrar</button> : topic.status === 'CLOSED' ? <button type="button" disabled={busy} onClick={() => void changeTopic(topic, 'reopen')} className="min-h-10 rounded-lg border px-3">Reabrir</button> : ['REPAIR_REQUIRED', 'CREATE_UNKNOWN'].includes(topic.status) ? <button type="button" disabled={busy} onClick={() => void recreate(topic)} className="min-h-10 rounded-lg border border-amber-300 px-3 text-amber-700">Recrear</button> : null}</div>) : <div className="rounded-lg border border-dashed border-slate-300 p-4 text-center text-xs text-slate-500 dark:border-slate-700">Este grupo todavía no tiene temas.</div>}</div>
        {addingTopic ? <div className="mt-3 rounded-lg bg-slate-50 p-3 dark:bg-slate-800/70"><p className="text-sm font-semibold">Crear tema por cliente</p><p className="mt-1 text-xs text-slate-500">Para registrar uno existente usa <code>/registrartema ID_CLIENTE</code>.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input aria-label="ID de cliente MikroWisp" value={clientId} onChange={e => { setClientId(e.target.value); setPreview(null); }} placeholder="ID del cliente" className="min-h-11 min-w-0 flex-1 rounded-lg border border-slate-200 px-3 text-sm dark:border-slate-700 dark:bg-slate-950" /><button type="button" disabled={busy || !clientId} onClick={() => void validateClient()} className="min-h-11 rounded-lg border border-violet-200 px-4 text-xs font-semibold">Validar cliente</button></div>{preview ? <div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-900"><p>Vista previa: <b>{preview.topicName}</b></p><button type="button" onClick={() => void createTopic()} className="mt-2 min-h-10 rounded-lg bg-emerald-600 px-3 font-semibold text-white">Confirmar creación</button></div> : null}</div> : null}
      </div>
      <div className="border-t border-slate-100 pt-4 dark:border-slate-800"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-slate-500" /><h4 className="text-sm font-bold">Participantes conocidos</h4></div><p className="mt-1 text-xs text-slate-500">Usuarios observados por el bot; no es el censo completo de Telegram.</p><div className="mt-3 space-y-2">{participants.map(p => <div key={p.userId} className="rounded-lg border border-slate-200 p-3 text-xs dark:border-slate-700"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold">{p.name || p.email}</p><p className="mt-1 text-slate-500">{p.telegramLinked ? label(p.status) : 'Telegram no vinculado'}</p></div>{p.telegramLinked && p.status === 'NOT_INVITED' ? <button type="button" onClick={() => void participantAction(p, 'invite')} className="min-h-10 rounded-lg border px-3">Invitar</button> : p.status === 'ACTIVE' ? <button type="button" onClick={() => void participantAction(p, 'remove')} className="min-h-10 rounded-lg border border-rose-300 px-3 text-rose-700">Retirar</button> : p.status === 'REMOVED' ? <button type="button" onClick={() => void participantAction(p, 'reinstate')} className="min-h-10 rounded-lg border px-3">Reintegrar</button> : null}</div>{p.inviteLink ? <a className="mt-2 block break-all rounded bg-slate-100 p-2 text-violet-700 underline dark:bg-slate-800 dark:text-violet-300" href={p.inviteLink} target="_blank" rel="noreferrer">Abrir invitación individual</a> : null}</div>)}</div></div>
    </section> : null}

    <section className="rounded-xl border border-dashed border-violet-300 bg-white p-3 dark:border-violet-700 dark:bg-slate-900" aria-labelledby="add-group-heading"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 id="add-group-heading" className="text-sm font-bold">Agregar nuevo grupo</h3><p className="mt-1 text-xs text-slate-500">Vincula otro supergrupo privado cuando lo necesites.</p></div><button type="button" onClick={() => setAddingGroup(v => !v)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-violet-600 px-4 text-xs font-semibold text-white"><FolderPlus className="h-4 w-4" />{addingGroup ? 'Ocultar pasos' : 'Agregar grupo'}</button></div>
      {addingGroup ? <div className="mt-4 border-t border-slate-100 pt-4 dark:border-slate-800"><p className="text-xs text-slate-600 dark:text-slate-300">Usa el mismo bot del workspace; no necesitas crear otro.</p><ol className="mt-3 list-decimal space-y-1.5 pl-5 text-xs text-slate-700 dark:text-slate-200"><li>Crea un grupo privado en Telegram.</li><li>Activa <b>Temas</b>.</li><li>Agrega el bot de Joinpoint como administrador.</li><li>Concede permisos para temas, invitaciones y restricciones.</li><li>Genera el código y envíalo dentro del grupo.</li></ol><div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void generateLink()} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-violet-600 px-4 text-xs font-semibold text-white"><FolderPlus className="h-4 w-4" />Generar código</button>{guide ? <a href="/api/workspace/integrations/mikrowisp/guide/download" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-violet-200 px-3 text-xs font-semibold text-violet-700"><ExternalLink className="h-4 w-4" />Ver guía PDF · {guide.version}</a> : null}</div>{link ? <div className="mt-3 rounded-lg bg-slate-100 p-3 text-xs dark:bg-slate-800"><p className="font-semibold">Envía este comando dentro del supergrupo:</p><code className="mt-2 block select-all rounded bg-white p-2 text-sm dark:bg-slate-950">{link.command}</code><p className="mt-1 text-slate-500">Vence: {new Date(link.expiresAt).toLocaleTimeString('es-PE')}</p></div> : null}</div> : null}
    </section>
    {busy ? <p className="flex items-center text-xs"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Procesando…</p> : null}{message ? <p role="status" className="rounded-lg bg-violet-100 p-2.5 text-xs text-violet-900 dark:bg-violet-500/15 dark:text-violet-100">{message}</p> : null}
  </div>;
}
