import { useCallback, useEffect, useMemo, useState } from 'react';
import { Shield, ShieldCheck, ShieldOff, RefreshCw, Search, Ban, Unlock } from 'lucide-react';
import { confirmGoogleIdentity } from '../../../services/federatedAuth';
import { securityAdminApi, type SecurityJail, type SecurityMutation } from '../../../services/securityAdminApi';

const categories: Array<[SecurityMutation['category'], string]> = [
  ['FALSE_POSITIVE','Falso positivo'], ['ADMIN_ACCESS','Acceso administrativo'],
  ['MAINTENANCE','Mantenimiento'], ['SECURITY_TEST','Prueba de seguridad'], ['OTHER','Otro'],
];

export default function SecurityModule() {
  const [jails,setJails]=useState<SecurityJail[]>([]); const [trusted,setTrusted]=useState<string[]>([]);
  const [currentIp,setCurrentIp]=useState('');
  const [history,setHistory]=useState<Array<Record<string,unknown>>>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [filter,setFilter]=useState('');
  const [action,setAction]=useState<'ban'|'unban'|'trust'|'untrust'|null>(null);
  const [target,setTarget]=useState(''); const [jail,setJail]=useState('sshd');
  const [duration,setDuration]=useState<SecurityMutation['duration']>('1h');
  const [category,setCategory]=useState<SecurityMutation['category']>('FALSE_POSITIVE');
  const [reason,setReason]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [confirmRisk,setConfirmRisk]=useState(false);
  const [attempts,setAttempts]=useState<Array<Record<string,unknown>>|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [s,h]=await Promise.all([securityAdminApi.status(),securityAdminApi.history()]);setJails(s.jails);setTrusted(s.trusted);setCurrentIp(s.currentIp);setHistory(h.history);}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const rows=useMemo(()=>jails.flatMap(j=>j.banned.map(ip=>{const d=j.banDetails?.find(x=>x.target===ip);return {ip,jail:j.name,protection:d?.reason||(j.name==='sshd'?'Fallos SSH':'Bloqueo manual'),attempts:d?.attempts??0,blockedSince:d?.blockedSince,expiresAt:d?.expiresAt};}))
    .filter(r=>!filter||r.ip.includes(filter)||r.jail.includes(filter)),[jails,filter]);
  const open=(kind:typeof action,ip='',sourceJail='sshd')=>{setAction(kind);setTarget(ip);setJail(sourceJail);setReason('');setPassword('');setConfirmRisk(false);};
  const showAttempts=async(ip:string)=>{setError('');try{const data=await securityAdminApi.attempts(ip);setAttempts(data.attempts);}catch(e){setError(e instanceof Error?e.message:'No se pudieron consultar los intentos');}};
  const execute=async(google=false)=>{if(!action||reason.trim().length<10)return;setBusy(true);setError('');try{
    const proof=google?await securityAdminApi.stepUpGoogle(await confirmGoogleIdentity()):await securityAdminApi.stepUpPassword(password);
    const data:SecurityMutation={target,jail,duration,category,reason:reason.trim(),stepUpToken:proof.stepUpToken,confirmIndefinite:duration==='indefinite'&&confirmRisk,confirmNetworkTrust:action==='trust'&&target.includes('/')&&confirmRisk};
    if(action==='ban')await securityAdminApi.ban(data); if(action==='unban')await securityAdminApi.unban(data);
    if(action==='trust')await securityAdminApi.trust(data); if(action==='untrust')await securityAdminApi.untrust(data);
    setAction(null);await load();
  }catch(e){setError(e instanceof Error?e.message:'Operación fallida');}finally{setBusy(false);}};
  return <div className="space-y-5 p-4 md:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">Seguridad del VPS</h1><p className="text-sm text-slate-500">Bloqueos Fail2ban, intentos SSH y direcciones confiables.</p></div><button className="btn-secondary" onClick={()=>void load()} disabled={loading}><RefreshCw className="h-4 w-4"/> Actualizar</button></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-3"><Summary icon={Shield} label="Bloqueadas" value={rows.length}/><Summary icon={ShieldCheck} label="Confiables" value={trusted.length}/><Summary icon={ShieldOff} label="Jails activos" value={jails.length}/></div>
    <div className="card p-4"><div className="mb-4 flex flex-wrap gap-2"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input className="input-field pl-9" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Buscar IP o servicio"/></div><button className="btn-primary" onClick={()=>open('ban')}><Ban className="h-4 w-4"/> Bloquear IP</button><button className="btn-secondary" onClick={()=>open('trust')}><ShieldCheck className="h-4 w-4"/> Agregar confiable</button></div>
      <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr>{['IP','Motivo / protección','Intentos','Bloqueada desde','Expira','Jail','Acción'].map(h=><th key={h} className="th-cell">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={`${r.jail}-${r.ip}`}><td className="data-cell font-mono">{r.ip}</td><td className="data-cell">{r.protection}</td><td className="data-cell">{r.attempts}</td><td className="data-cell">{r.blockedSince?new Date(r.blockedSince).toLocaleString('es-PE'):'—'}</td><td className="data-cell">{r.expiresAt===null?'Indefinido':r.expiresAt?new Date(r.expiresAt).toLocaleString('es-PE'):'—'}</td><td className="data-cell font-mono text-xs">{r.jail}</td><td className="data-cell"><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>void showAttempts(r.ip)}>Intentos</button><button className="btn-secondary" onClick={()=>open('trust',r.ip)}><ShieldCheck className="h-4 w-4"/> Confiar</button><button className="btn-secondary" onClick={()=>open('unban',r.ip,r.jail)}><Unlock className="h-4 w-4"/> Desbloquear</button></div></td></tr>)}{!loading&&rows.length===0&&<tr><td colSpan={7} className="p-8 text-center text-slate-500">No hay direcciones bloqueadas.</td></tr>}</tbody></table></div>
    </div>
    <div className="card p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">Lista confiable permanente</h2>{currentIp&&<button className="btn-secondary" onClick={()=>open('trust',currentIp)}>Confiar en mi IP actual</button>}</div><div className="flex flex-wrap gap-2">{trusted.map(ip=><span key={ip} className="badge-success flex items-center gap-2 font-mono">{ip}<button aria-label={`Retirar ${ip}`} onClick={()=>open('untrust',ip)}>×</button></span>)}{trusted.length===0&&<span className="text-sm text-slate-500">Sin excepciones adicionales.</span>}</div></div>
    <div className="card overflow-hidden"><div className="border-b border-slate-200 p-4 dark:border-slate-700"><h2 className="font-bold">Actividad reciente</h2><p className="text-xs text-slate-500">Quién realizó cada cambio, desde qué IP y con qué motivo.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr>{['Fecha','Administrador','Acción','Objetivo','Resultado','Motivo'].map(h=><th key={h} className="th-cell">{h}</th>)}</tr></thead><tbody>{history.slice(0,25).map((row,i)=><tr key={String(row.id||i)}><td className="data-cell whitespace-nowrap">{row.created_at?new Date(Number(row.created_at)).toLocaleString('es-PE'):'—'}</td><td className="data-cell">{String(row.actor_email||'Administrador')}</td><td className="data-cell font-mono text-xs">{String(row.action||'')}</td><td className="data-cell font-mono text-xs">{String(row.target||'—')}</td><td className="data-cell">{row.outcome==='SUCCESS'?'Aplicado':'Falló'}</td><td className="data-cell max-w-sm">{String(row.reason||'')}</td></tr>)}{history.length===0&&<tr><td colSpan={6} className="p-6 text-center text-slate-500">Aún no hay acciones administrativas.</td></tr>}</tbody></table></div></div>
    {action&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><div className="card w-full max-w-lg space-y-4 p-5"><h2 className="text-lg font-bold">Confirmar acción de seguridad</h2><label className="block text-sm font-semibold">IP o red<input className="input-field mt-1 font-mono" value={target} onChange={e=>setTarget(e.target.value)} disabled={action==='unban'||action==='untrust'}/></label>{action==='ban'&&<label className="block text-sm font-semibold">Duración<select className="input-field mt-1" value={duration} onChange={e=>{setDuration(e.target.value as SecurityMutation['duration']);setConfirmRisk(false);}}>{['15m','1h','6h','24h','7d','indefinite'].map(v=><option key={v} value={v}>{v==='indefinite'?'Indefinido':v}</option>)}</select></label>}<label className="block text-sm font-semibold">Categoría<select className="input-field mt-1" value={category} onChange={e=>setCategory(e.target.value as SecurityMutation['category'])}>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="block text-sm font-semibold">Motivo<input className="input-field mt-1" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Mínimo 10 caracteres"/></label><label className="block text-sm font-semibold">Contraseña actual<input type="password" className="input-field mt-1" value={password} onChange={e=>setPassword(e.target.value)}/></label>{(action==='trust'||duration==='indefinite')&&<div className="rounded-lg bg-amber-50 p-3 text-xs text-amber-800"><p>Esta acción permanece hasta retirarla manualmente. Verifica cuidadosamente el objetivo.</p>{(duration==='indefinite'||(action==='trust'&&target.includes('/')))&&<label className="mt-2 flex gap-2 font-semibold"><input type="checkbox" checked={confirmRisk} onChange={e=>setConfirmRisk(e.target.checked)}/> Confirmo el alcance y el riesgo de esta excepción permanente.</label>}</div>}<div className="flex flex-wrap justify-end gap-2"><button className="btn-secondary" onClick={()=>setAction(null)}>Cancelar</button><button className="btn-secondary" disabled={busy||reason.trim().length<10||(duration==='indefinite'&&!confirmRisk)||(action==='trust'&&target.includes('/')&&!confirmRisk)} onClick={()=>void execute(true)}>Confirmar con Google</button><button className="btn-primary" disabled={busy||!password||reason.trim().length<10||(duration==='indefinite'&&!confirmRisk)||(action==='trust'&&target.includes('/')&&!confirmRisk)} onClick={()=>void execute(false)}>{busy?'Aplicando…':'Confirmar'}</button></div></div></div>}
    {attempts&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><div className="card max-h-[80vh] w-full max-w-2xl overflow-auto p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Intentos SSH recientes</h2><button className="btn-secondary" onClick={()=>setAttempts(null)}>Cerrar</button></div><div className="space-y-2">{attempts.map((row,i)=><div key={i} className="rounded-lg bg-slate-50 p-3 font-mono text-xs dark:bg-slate-900">{String(row.message||'')}</div>)}{attempts.length===0&&<p className="text-sm text-slate-500">No se encontraron intentos en las últimas 24 horas.</p>}</div></div></div>}
  </div>;
}

function Summary({icon:Icon,label,value}:{icon:typeof Shield;label:string;value:number}){return <div className="card flex items-center gap-3 p-4"><div className="rounded-xl bg-indigo-50 p-2 text-indigo-600"><Icon className="h-5 w-5"/></div><div><div className="text-2xl font-bold">{value}</div><div className="text-xs text-slate-500">{label}</div></div></div>}
