import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Building2, KeyRound, LayoutDashboard, Lock, LogOut, Mail, Network, PackageCheck, Plus, RefreshCw, Server, ShieldCheck, UserRound } from 'lucide-react';
import { centralApi, type Admin, type Customer, type Instance, type Plan } from './api';

type Tab='overview'|'customers'|'plans'|'instances';
export default function App(){
  const [admin,setAdmin]=useState<Admin|null>(null); const [checking,setChecking]=useState(true);
  useEffect(()=>{centralApi.me().then(setAdmin).catch(()=>setAdmin(null)).finally(()=>setChecking(false));},[]);
  if(checking) return <Loading/>;
  if(!admin) return <Login onLogin={setAdmin}/>;
  return <Console admin={admin} onLogout={()=>setAdmin(null)}/>;
}

function Loading(){return <main className="center"><div className="brand-mark"><Network/></div><p>Iniciando Joinpoint Central…</p></main>}
function Login({onLogin}:{onLogin:(admin:Admin)=>void}){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [totp,setTotp]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{onLogin(await centralApi.login(email.trim(),password,totp));}catch(e){setError(e instanceof Error?e.message:'Acceso denegado.');}finally{setBusy(false)}}
  return <main className="legacy-login-page"><div className="login-glow login-glow-a"/><div className="login-glow login-glow-b"/><section className="legacy-login-shell"><div className="legacy-login-form"><form onSubmit={submit}><header className="legacy-login-heading"><span className="eyebrow">Bienvenido de nuevo</span><h1>Inicia sesión</h1><p>Usa tus credenciales para entrar a tu centro de operaciones.</p></header>{error?<div className="error login-error" role="alert">{error}</div>:null}<div className="legacy-fields"><label>Correo<div className="input-with-icon"><UserRound/><input autoFocus type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="administrador@joinpoint.cloud"/></div></label><label>Contraseña<div className="input-with-icon"><Lock/><input type="password" minLength={12} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••"/></div></label><label>Código de autenticación<div className="input-with-icon"><ShieldCheck/><input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" value={totp} onChange={e=>setTotp(e.target.value.replace(/\D/g,''))} required placeholder="000000"/></div></label></div><button className="legacy-submit" disabled={busy||totp.length!==6}><span className="button-shine"/><Server/>{busy?'Verificando…':'Ingresar a Joinpoint'}</button><p className="secure-copy"><Lock/> Operación segura · Monitoreo centralizado · MFA</p></form></div><aside className="legacy-login-brand" aria-label="Joinpoint Central"><span className="brand-orbit brand-orbit-top"/><span className="brand-orbit brand-orbit-bottom"/><div className="brand-content"><div className="logo-glass"><JoinpointLogo inverted/></div><span className="brand-kicker">JOINPOINT CENTRAL</span><h2>¡Hola de nuevo!</h2><p>Administra clientes, membresías e instancias desde una plataforma segura.</p><div className="brand-feature"><Mail/><span>Control comercial y operativo</span></div></div></aside></section></main>
}

function JoinpointLogo({inverted=false}:{inverted?:boolean}){const primary=inverted?'#fff':'#3157D5';const accent=inverted?'#9DECF0':'#16B8C4';return <svg viewBox="0 0 64 64" role="img" aria-label="Joinpoint" fill="none"><rect width="64" height="64" rx="18" fill={inverted?'rgba(255,255,255,.14)':'#EEF2FF'}/><path d="M42 15v25c0 8.3-6.7 15-15 15-7.2 0-13-4.7-15-11.2" stroke={primary} strokeWidth="7" strokeLinecap="round"/><path d="M23 25h19" stroke={primary} strokeWidth="7" strokeLinecap="round"/><circle cx="42" cy="15" r="5" fill={accent}/><circle cx="23" cy="25" r="5" fill={accent}/><circle cx="12" cy="43" r="5" fill={accent}/></svg>}

function Console({admin,onLogout}:{admin:Admin;onLogout:()=>void}){
 const [tab,setTab]=useState<Tab>('overview');const [data,setData]=useState<[Customer[],Plan[],Instance[]]>([[],[],[]]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(()=>{setLoading(true);setError('');centralApi.overview().then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);useEffect(load,[load]);
 async function logout(){try{await centralApi.logout();}finally{onLogout()}}
 const nav:[Tab,string,typeof LayoutDashboard][]=[['overview','Resumen',LayoutDashboard],['customers','Clientes',Building2],['plans','Planes',PackageCheck],['instances','Instancias',Server]];
 return <div className="app-shell"><aside><div className="wordmark"><span className="sidebar-logo"><JoinpointLogo/></span><div><strong>JOINPOINT <em>CENTRAL</em></strong><small>Tu negocio, bajo control</small></div></div><small>PLATAFORMA</small><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</nav><div className="account"><span>{admin.displayName}</span><small>{admin.email}</small><button onClick={logout}><LogOut/>Cerrar sesión</button></div></aside><main className="content"><header><div><span className="eyebrow">Administrador</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><button className="secondary" onClick={load} disabled={loading}><RefreshCw/>Actualizar</button></header>{error?<div className="error">{error}</div>:null}{loading?<div className="skeleton-grid"><i/><i/><i/></div>:<TabContent tab={tab} data={data} reload={load}/>}</main></div>
}

function TabContent({tab,data,reload}:{tab:Tab;data:[Customer[],Plan[],Instance[]];reload:()=>void}){const [customers,plans,instances]=data;if(tab==='overview')return <><section className="metrics"><Metric icon={Building2} label="Clientes" value={customers.length}/><Metric icon={PackageCheck} label="Planes" value={plans.length}/><Metric icon={Server} label="Instancias" value={instances.length}/><Metric icon={KeyRound} label="Activas" value={instances.filter(x=>x.status==='ACTIVE').length}/></section><section className="card"><h2>Estado de la plataforma</h2><div className="healthy"><ShieldCheck/>Servicios centrales operativos</div><p className="muted">El siguiente paso es registrar el primer cliente, asignar un plan y preparar su instancia.</p></section></>;if(tab==='customers')return <Resource title="Clientes" action={<CustomerForm done={reload}/>} empty="Todavía no hay clientes."><Table headers={['Nombre','Razón social','Identificación','Estado']} rows={customers.map(x=>[x.display_name,x.legal_name,x.tax_id||'—',x.status])}/></Resource>;if(tab==='plans')return <Resource title="Planes" action={<PlanForm done={reload}/>} empty="Todavía no hay planes."><Table headers={['Código','Nombre','Descripción','Estado']} rows={plans.map(x=>[x.code,x.name,x.description||'—',x.status])}/></Resource>;return <Resource title="Instancias" action={<InstanceForm customers={customers} done={reload}/>} empty="Todavía no hay instancias."><Table headers={['Dominio','IP pública','Pool','Estado']} rows={instances.map(x=>[x.fqdn,x.public_ip||'Pendiente',x.management_pool_cidr,x.status])}/></Resource>}
function Metric({icon:Icon,label,value}:{icon:typeof Server;label:string;value:number}){return <article className="metric"><span><Icon/></span><div><small>{label}</small><strong>{value}</strong></div></article>}
function Resource({title,action,empty,children}:{title:string;action:React.ReactNode;empty:string;children:React.ReactNode}){return <section className="card"><div className="card-head"><div><h2>{title}</h2><p className="muted">Información gestionada por la plataforma central.</p></div>{action}</div>{children||<p>{empty}</p>}</section>}
function Table({headers,rows}:{headers:string[];rows:string[][]}){if(!rows.length)return <div className="empty">Sin registros todavía.</div>;return <div className="table-wrap"><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function CustomerForm({done}:{done:()=>void}){return <QuickCreate label="Nuevo cliente" fields={[['legalName','Razón social'],['displayName','Nombre visible'],['taxId','RUC / identificación']]} submit={centralApi.createCustomer} done={done}/>}
function PlanForm({done}:{done:()=>void}){return <QuickCreate label="Nuevo plan" fields={[['code','Código'],['name','Nombre'],['description','Descripción']]} map={v=>({...v,entitlements:[]})} submit={centralApi.createPlan} done={done}/>}
function InstanceForm({customers,done}:{customers:Customer[];done:()=>void}){if(!customers.length)return <button className="primary" disabled><Plus/>Primero crea un cliente</button>;return <QuickCreate label="Nueva instancia" fields={[['customerId','ID del cliente'],['subdomainLabel','Subdominio'],['publicIp','IP pública']]} defaults={{customerId:customers[0].id}} submit={centralApi.createInstance} done={done}/>}
function QuickCreate({label,fields,defaults={},map=(x)=>x,submit,done}:{label:string;fields:string[][];defaults?:Record<string,string>;map?:(x:any)=>any;submit:(x:any)=>Promise<unknown>;done:()=>void}){const [open,setOpen]=useState(false);const [values,setValues]=useState<Record<string,string>>(defaults);const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await submit(map(Object.fromEntries(Object.entries(values).filter(([,v])=>v))));setOpen(false);done();}catch(err){setError(err instanceof Error?err.message:'No se pudo guardar.')}finally{setBusy(false)}}if(!open)return <button className="primary" onClick={()=>setOpen(true)}><Plus/>{label}</button>;return <form className="inline-form" onSubmit={save}>{fields.map(([key,text])=><input key={key} required={key!=='taxId'&&key!=='description'&&key!=='subdomainLabel'&&key!=='publicIp'} placeholder={text} value={values[key]||''} onChange={e=>setValues({...values,[key]:e.target.value})}/>)}{error?<span className="error">{error}</span>:null}<button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar'}</button><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button></form>}
