[gestionvpn-web-1h]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = 1h
action = ufw

[gestionvpn-web-scan-6h]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = 6h
action = ufw

[gestionvpn-web-scan-24h]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = 24h
action = ufw
