[gestionvpn-15m]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = 15m
action = ufw

[gestionvpn-1h]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = 1h
action = ufw

[gestionvpn-6h]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = 6h
action = ufw

[gestionvpn-24h]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = 24h
action = ufw

[gestionvpn-7d]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = 7d
action = ufw

[gestionvpn-indefinite]
enabled = true
filter = sshd
backend = systemd
maxretry = 999999
bantime = -1
action = ufw
